### ISSUE TITLE
Localised slug/routes support

### ISSUE THREAD

**Issue by bpaugam** [getgrav/grav-plugin-langswitcher#1]
The provided langswitcher template always redirects to the default locale route (non-localised).

Example :

_01.page-1_
|---- _default.en.md_ with slug: first-page, ie route is `/en/first-page`
|---- _default.fr.md_ with slug: premiere-page ie route is `/fr/premiere-page`

When on `/en/first-page`, the lang-switcher will redirect either on `/en/first-page` [EN link] or `/fr/first-page` [FR link]

The "better" way would be to display both localised link : `/en/first-page` [EN link] and `/fr/premiere-page` [FR link]

**Comment by rhukster** [comment]
There is a very good reason for this.  When your on the english page for example, Grav has no idea what the french route is.  In fact, it only knows that a french page exists. The actual french page is not available to the english page.  This is because for performance reasons, each language has it's own cached pages/routes/etc, and only one language is ever loaded/processed at a time.

The only option is to have Grav automatically redirect from the raw route (which is used to find the french page at all), to the default route of the page.  To be honest I thought I had this option implemented already and tested, but now i'm not seeing it.  So perhaps I removed this because it was causing other problems.  I'll look back in my history and see what happened.

**Comment by rhukster** [comment]
BTW, this would be a modification to Grav, not the lang switcher.

**Comment by rhukster** [comment]
BTW, i just checked and this redirect is already implemented :) So the link may go to `/fr/first-page` but then it gets redirected to `/fr/premiere-page`
