### ISSUE TITLE
Mouse over show wrong url

### ISSUE THREAD

**Issue by Neuronauten** [getgrav/grav-plugin-langswitcher#17]
I don't know if it is a plugin or grav issue, please address.

In multilingual environment the url on mouse over the language switcher shows folder based urls but the link itself directs correctly to the slug set url.

**Comment by rhukster** [comment]
As outlined in numerous places, Grav doesn't know about the specific routes for other languages. It only knows about the current language.  it has be designed this way for performance reasons.

This is why the langswitcher uses the `raw_route` of the page, then it can optionally redirect to the default page once that language is active and loaded.  This is not a bug, it's intentional.

**Comment by Neuronauten** [comment]
Hallo Andy.
If it was just working i would not disturb you with my unqualified report. Technically I do not understand what you answered me. 
If you tell me that this result is not a bug but intended i have to say you that grav is not to usable because it shows every single attentive Visitor the incompetence (or unwillingness or however) of the code maker. Are you sure you understand the issue ? Maybe there is a place in grav where i can switch off the text which is shown on mouse over ?

**Comment by rhukster** [comment]
I'm pretty sure I understand what you saying.  The actual link is the raw-route, and the page will redirect to the default-route if it exists.  This is something that is done quite infrequently because people generally don't jump between multiple languages.  once your are in a language, all the routes are correct.

You can't change the text of a hyperlink because that's a browser feature.

**Comment by Neuronauten** [comment]
I could reproduce that. It is only on the not active languages. It is not nice but like you said not commonly needed. Thanks for your time.

**Comment by rhukster** [comment]
You have to make sure you have "Redirect to default route" option set in your `user/config/system.yaml`: https://github.com/getgrav/grav/blob/develop/system/config/system.yaml#L57
