### ISSUE TITLE
Support slugs in links

### ISSUE THREAD

**Issue by attiks** [getgrav/grav-plugin-langswitcher#2]
I have a site with 2 languages:
- nl (default)
- en

Dutch page is in folder diensten
English page has a slug services

On a Dutch page the links are
- nl/diensten
- en/diensten

On a English page the links are
- nl/diensten
- en/services

It would be nice if the links would use the slugs

**Comment by rhukster** [comment]
Due to limitations in the multilanguage implementation, the links MUST use the **raw route** for the page because each language doesn't know anything about the custom slug routes in other languages.  

You can however, enable the **redirect to default route** which will redirect to the default route for the page (including custom slugs).

**Comment by attiks** [comment]
Thanks, didn't know about the `redirect_default_route`
